# Generated by Django 4.0.4 on 2022-09-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_editora_formato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_lancamento', models.DateField()),
                ('isbn', models.CharField(max_length=255)),
                ('numero_paginas', models.PositiveIntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.editora')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formato')),
            ],
        ),
    ]
