# Generated by Django 4.0.4 on 2022-09-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente_aluguel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aluguel',
        ),
    ]
