# Generated by Django 4.0.4 on 2022-09-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
